#!/usr/bin/env bash

# This is a test executable that simulates, for testing purposes, the byte
# protocol sent by the bme280 C to Elixir binding provided by this project.

while read line
do
  if [ "$line" = 'measure' ]; then
    printf "T:021.54,P:0030.52,H:0045.72\n"
  else
    >&2 echo "bme280 test executable: invalid command"
    exit -1
  fi
done
